version: '3.8'
services:
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3000:3000"
      - "50051:50051"

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3001:3001"
      - "50052:50052"
    depends_on:
      - product-service
